language: python
    - "2.7"
addons:
    apt:
        packages:
            - python-opencv
            - python-cffi
cache: pip
install:
    - pip install numpy codecov rednose nose coverage nose-parameterized --upgrade
    - pip install .
script: nosetests
dist: trusty
after_success:
    codecov
