language: python
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-pip python-numpy python-scipy python-opencv python-cffi
    - sudo pip install codecov rednose nose coverage nose-parameterized --upgrade
cache: pip
script: nosetests
dist: trusty
after_success:
    codecov
