language: python
    - "2.7"
cache: pip
install:
    - pip install numpy codecov rednose nose coverage nose-parameterized opencv-python cffi
    - pip install .
script: nosetests
dist: trusty
sudo: false
after_success:
    codecov
